export default interface Task
{
    id: string,
    user_id: string,
    project_id: string,
    section_id: string | null,
    parent_id: string | null,
    added_by_uid: string,
    assigned_by_uid: string | null,
    responsible_uid: string | null,
    labels: string[],
    deadline: any | null,
    duration: any | null,
    checked: boolean,
    is_deleted: boolean,
    added_at: string,
    completed_at: string | null,
    updated_at: string,
    due?: {
        date: string,
        string: string,
        is_recurring: boolean,
    },
    priority: number,
    child_order: number,
    content: string,
    description: string,
    note_count: number,
    day_order: number,
    is_collapsed: boolean,
};